a, b, c = (1, 2, 3)
d, e, _ = (1, 2, 3)
f, *j = (1, 2, 3, 4)
k, *l, m = (1, 2, 3, 4, 5)
n, *_ = (1, 2, 3, 4, 5, 6)

print(a)
print(b)
print(c)
print("d,e:", d, e)
print("f: ", f)
print('j: ', j)
print(f'k: {k}')
print('l: ', l)
print('m: ', m)
print('n: ', n)
